services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: website:latest
    container_name: website-container
    ports:
      - "8098:8098"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=8098
      - HOSTNAME=0.0.0.0
    restart: unless-stopped

